name: CI Checks

on:
  push:
    branches: [ main, test, feature/**, fix/** ]
  pull_request:
    branches: [ main, test ]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.16.0  # 指定 pnpm 版本，可以省略或改为 latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'pnpm'

      - name: Install and test
        run: |
          pnpm install
          pnpm lint
          pnpm build
    